title: Bhaswan's portfolio
#description: A short description of your site
theme: jekyll-theme-minimalist
#logo: /assets/images/logo.png
# Optional settings
show_downloads: false
plugins:
  - jekyll-feed
