title: Bhaswan Gopalakaje - Portfolio
#description: Portfolio
logo: /assets/images/Bhaswanlogo.png
theme: jekyll-theme-leap-day
show_downloads: true
github:
  repository_url: https://github.com/YOUR-USERNAME
plugins:
  - jekyll-feed
